<<<<<<< HEAD

=======
>>>>>>> 9d025bc811f63a4106d885e825c4d7fb7e83a8c4
name: hello-udst
on: push
jobs:
  hello-udst-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print Hello UDST Message
        run: echo "Hello UDST!"
